SELECT MIN(CODFUN) #BUSCA O MENOR VALOR DA COLUNA
FROM CADFUN;

SELECT MAX(CODFUN)  #BUSCA O MAIOR VALOR DA COLUNA
FROM CADFUN;

SELECT MIN(DATE_FORMAT(DTANASC, '%d/%m/%Y')) AS "Data de Nascimento Mais Antiga" #BUSCA A MENOR DATA E RETORNA O VALOR FORMATADO
FROM CADFUN;

SELECT MAX(SALHORA) AS "Maior Salário" #BUSCA O MAIOR SALÁRIO HORA DA COLUNA
FROM CADFUN;

SELECT MIN(SALHORA) AS "Menor Salário" #BUSCA O MENOR SALÁRIO HORA DA COLUNA
FROM CADFUN;

SELECT SUM(SALHORA) AS "Somatório de Salário" #RETORNA OS VALORES DA COLUNA SOMADOS
FROM CADFUN
GROUP BY SEXO;

SELECT CODFUN, NOME
FROM CADFUN;

UPDATE  CADFUN 
SET SEXO = 'M'
WHERE CODFUN IN (8720028, 8720009);
