SELECT MIN(CODFUN) #BUSCA O MENOR VALOR DA COLUNA
FROM CADFUN;

SELECT MAX(CODFUN)  #BUSCA O MAIOR VALOR DA COLUNA
FROM CADFUN;

SELECT MIN(DATE_FORMAT(DTANASC, '%d/%m/%Y')) AS "Data de Nascimento Mais Antiga" #BUSCA A MENOR DATA E RETORNA O VALOR FORMATADO
FROM CADFUN;

SELECT MAX(SALHORA) AS "Maior Salário" #BUSCA O MAIOR SALÁRIO HORA DA COLUNA
FROM CADFUN;

SELECT MIN(SALHORA) AS "Menor Salário" #BUSCA O MENOR SALÁRIO HORA DA COLUNA
FROM CADFUN;

SELECT CASE SEXO WHEN 'M' THEN 'MASCULINO' ELSE 'FEMININO' END ,	 #CASO SEXO CONTENHA M, RETORNA MASCULINO, SENÃO RETORNA FEMININO E RETORNA OS VALORES DA COLUNA SALHORA SOMADOS, AMBOS ORDENADOS POR SEXO
			SUM(SALHORA) AS "Somatório de Salário"
FROM CADFUN
GROUP BY SEXO;


SELECT CODCARGO, COUNT(CODFUN) #RETORNA A QUANTIDADE DE FUNCIONARIOS, AGRUPADOS POR CODIGO DO CARGO
FROM CADFUN
GROUP BY CODCARGO;


SELECT ESTCIVIL, MIN(DATE_FORMAT(DTANASC, '%d/%m/%Y')) #RETORNA OS FUNCIONARIOS MAIS VELHOS AGRUPADOS POR ESTADO CIVIL
FROM CADFUN
GROUP BY ESTCIVIL;

SELECT DATE_FORMAT(DTAFOLHA, '%d/%m/%Y'), SUM(QTDHORAS) #RETORNA A SOMATÓRIA DA COLUNA QTDHORAS AGRUPADOS POR DATA DA FOLHA
FROM LCTFOLHA
GROUP BY DTAFOLHA;


SELECT DATE_FORMAT(DTAFOLHA, '%d/%m/%Y'), SUM(QTDHORAS)
FROM LCTFOLHA
GROUP BY DTAFOLHA
HAVING AVG(QTDHORA) > 178
ORDER BY 1;



INSERT INTO LCTFOLHA (CODFUN, DTAFOLHA, TIPOSAL, QTDHORAS)
			VALUES (8720028,'2021-01-31', 'MENSAL', 176);
UPDATE LCTFOLHA
SET DTAFOLHA = '2021-01-21'
WHERE CODFUN = 8720009;

UPDATE LCTFOLHA
SET DTAFOLHA = '2021-01-21'
WHERE CODFUN = 8720029;

UPDATE CADFUN
SET ESTCIVIL = 'SOLTEIRO'
WHERE CODFUN = 8720028;

UPDATE  CADFUN 
SET SEXO = 'M'
WHERE CODFUN IN (8720028, 8720009);
